hwi_oauth:
    firewall_names: [main]

    resource_owners:
        facebook:
            type: facebook
            client_id: '%env(FB_ID)%'
            client_secret: '%env(FB_SECRET)%'
            scope: "email public_profile"
            options:
                display: popup
                auth_type: rerequest

        google:
            type: google
            client_id: '%env(GOOGLE_ID)%'
            client_secret: '%env(GOOGLE_SECRET)%'
            scope: "email profile"
            options:
                access_type: offline

    connect:
        account_connector: app.oauth_user_provider

    fosub:
        username_iterations: 30
        properties:
            facebook: facebookId
            google: googleId
